const courses = [
  {
    id: 1,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/1.jpg",
    category: "Development",
  },
  {
    id: 2,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/2.jpg",
    category: "Development",
  },
  {
    id: 3,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/3.jpg",
    category: "Development",
  },
  {
    id: 4,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/4.jpg",
    category: "Development",
  },
  {
    id: 5,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/5.png",
    category: "Development",
  },
  {
    id: 6,
    author: "Determined-Poitras",
    title: "Create an LMS Website with LearnPress",
    duration: "2 Weeks",
    students: 156,
    oldPrice: 29.0,
    newPrice: "Free",
    image: "/6.jpg",
    category: "Development",
  },
];
export default courses;
